/**
 * server/src/improvement/service.ts
 *
 * Skill self-improvement orchestration — M10.
 *
 * triggerImprovement()   — entry point: checks conditions, creates draft version.
 * activateSkillVersion() — post-benchmark step: applies Tier A/B activation rule.
 *
 * RULE (mirrors M9 Tier A / Tier B logic for skill versions):
 *   Tier A skill → new version goes to "pending_approval"; human must approve.
 *   Tier B skill → new version auto-activates (current → deprecated, new → active).
 *
 * CONSTRAINT: activateSkillVersion() MUST be called AFTER runBenchmark() has set
 *   a benchmarkScore on the draft row. Calling it on an un-benchmarked draft throws.
 */

import { eq, and } from "drizzle-orm";
import { skillVersions } from "@paperclipai/db";
import type { Db } from "@paperclipai/db";
import {
  shouldTriggerImprovement,
  createDraftVersion,
  getActiveVersion,
  bumpMinorVersion,
  type TriggerReason,
} from "./analyser.js";
import pino from "pino";

const logger = pino({ name: "improvement" });

// ── triggerImprovement ────────────────────────────────────────────────────────

export interface TriggerImprovementParams {
  companyId:        string;
  agentId:          string;
  skillType:        string;
  trustScore:       number;
  triggerReason:    TriggerReason | null;
  // Improved prompt body generated by the self-improvement agent
  newPromptBody:    string;
  newFrontmatter:   Record<string, unknown>;
}

export interface TriggerImprovementResult {
  triggered:      boolean;
  draftVersionId: string | null;
  reason:         string;
}

/**
 * Check conditions and create a draft skill version if improvement is warranted.
 * The benchmark runs separately (via BullMQ in M12) after this returns.
 */
export async function triggerImprovement(
  db: Db,
  params: TriggerImprovementParams,
): Promise<TriggerImprovementResult> {
  const { companyId, agentId, skillType, trustScore, triggerReason } = params;

  if (!shouldTriggerImprovement(trustScore, triggerReason)) {
    return { triggered: false, draftVersionId: null, reason: "threshold not reached" };
  }

  // Find the current active version to derive the next version number
  const active = await getActiveVersion(db, companyId, skillType);
  const nextVersion = bumpMinorVersion(active ? "1.0.0" : "0.0.0");

  const draftVersionId = await createDraftVersion(db, {
    companyId,
    skillType,
    version:          nextVersion,
    promptBody:       params.newPromptBody,
    frontmatter:      params.newFrontmatter,
    parentVersionId:  active?.id,
    createdByAgentId: agentId,
    triggerReason:    triggerReason ?? "manual",
  });

  logger.info(
    { companyId, agentId, skillType, draftVersionId, triggerReason },
    "improvement: draft skill version created",
  );

  return {
    triggered:      true,
    draftVersionId,
    reason: triggerReason ?? "manual",
  };
}

// ── activateSkillVersion ──────────────────────────────────────────────────────

export interface ActivateSkillVersionParams {
  companyId:         string;
  draftVersionId:    string;
  skillType:         string;
  /** From skill frontmatter — Tier A requires human approval */
  skillAutonomyTier: "A" | "B";
  /** BenchmarkDecision from runBenchmark() — must not be null */
  benchmarkDecision: "proceed" | "neutral" | "block";
}

export interface ActivateSkillVersionResult {
  activated:          boolean;
  pendingApproval:    boolean;
  blocked:            boolean;
  newStatus:          string;
}

/**
 * Apply the Tier A/B activation rule after a successful benchmark.
 *
 * MUST be called after runBenchmark() — throws if version has no benchmarkScore.
 *
 * Tier A + proceed/neutral → status = "pending_approval" (human approves in M13)
 * Tier B + proceed/neutral → status = "active" (current active → deprecated)
 * block (any tier)         → status = "blocked" (stays in history, not activated)
 */
export async function activateSkillVersion(
  db: Db,
  params: ActivateSkillVersionParams,
): Promise<ActivateSkillVersionResult> {
  const { companyId, draftVersionId, skillType, skillAutonomyTier, benchmarkDecision } = params;

  // Verify the version has been benchmarked
  const [draft] = await db
    .select({ benchmarkScore: skillVersions.benchmarkScore, status: skillVersions.status })
    .from(skillVersions)
    .where(eq(skillVersions.id, draftVersionId))
    .limit(1);

  if (!draft) {
    throw new Error(`Skill version ${draftVersionId} not found`);
  }
  if (draft.benchmarkScore === null) {
    throw new Error(
      `activateSkillVersion called before benchmark ran on version ${draftVersionId}`,
    );
  }

  // Block decision — no activation regardless of tier
  if (benchmarkDecision === "block") {
    await db
      .update(skillVersions)
      .set({ status: "blocked" })
      .where(eq(skillVersions.id, draftVersionId));

    logger.warn({ draftVersionId, skillType }, "improvement: version blocked by benchmark");
    return { activated: false, pendingApproval: false, blocked: true, newStatus: "blocked" };
  }

  // Proceed or neutral — apply tier rule
  if (skillAutonomyTier === "A") {
    // RULE: Tier A — NEVER auto-activate. Surface for human approval.
    await db
      .update(skillVersions)
      .set({ status: "pending_approval" })
      .where(eq(skillVersions.id, draftVersionId));

    logger.info({ draftVersionId, skillType }, "improvement: Tier A — pending human approval");
    return { activated: false, pendingApproval: true, blocked: false, newStatus: "pending_approval" };
  }

  // Tier B — auto-activate
  // 1. Deprecate the current active version
  await db
    .update(skillVersions)
    .set({ status: "deprecated" })
    .where(
      and(
        eq(skillVersions.companyId, companyId),
        eq(skillVersions.skillType, skillType),
        eq(skillVersions.status, "active"),
      ),
    );

  // 2. Activate the new version
  await db
    .update(skillVersions)
    .set({ status: "active", activatedAt: new Date() })
    .where(eq(skillVersions.id, draftVersionId));

  logger.info(
    { draftVersionId, skillType },
    "improvement: Tier B — skill version auto-activated",
  );

  return { activated: true, pendingApproval: false, blocked: false, newStatus: "active" };
}
